export type Game = {
  id: string;
  title: string;
  subtitle: string;
  score: number;
  tier: "一档" | "二档" | "三档";
  year: string;
  developer: string;
  publisher: string;
  releaseDate: string;
  genre: string;
  tags: string[];
  color: string;
  color2: string;
  mark: string;
  note: string;
  record?: string;
};

export const games: Game[] = [
  {
    id: "ff7-remake",
    title: "最终幻想 VII 重制版",
    subtitle: "FINAL FANTASY VII REMAKE",
    score: 9.9,
    tier: "一档",
    year: "2020",
    developer: "Square Enix",
    publisher: "Square Enix",
    releaseDate: "2020-04-10",
    genre: "动作角色扮演",
    tags: ["角色", "战斗", "叙事"],
    color: "#75b9d6",
    color2: "#243e5a",
    mark: "VII",
    note: "战斗、叙事、演出和人物塑造几乎没有短板。它不是抽象意义上的完美，而是最贴合我审美的一次完整体验。",
    record: "在我玩过的游戏中，综合体验的天花板",
  },
  {
    id: "ff7-rebirth",
    title: "最终幻想 VII 重生",
    subtitle: "FINAL FANTASY VII REBIRTH",
    score: 9.8,
    tier: "一档",
    year: "2024",
    developer: "Square Enix",
    publisher: "Square Enix",
    releaseDate: "2024-02-29",
    genre: "动作角色扮演",
    tags: ["冒险", "角色", "世界"],
    color: "#e9b96e",
    color2: "#584229",
    mark: "VII",
    note: "更辽阔、更自由，也更像一场与熟悉角色真正共同生活过的漫长旅行。内容密度极高，却始终保留情感温度。",
    record: "在我玩过的游戏中，队伍旅行感的天花板",
  },
  {
    id: "persona-5-royal",
    title: "女神异闻录 5 皇家版",
    subtitle: "PERSONA 5 ROYAL",
    score: 9.8,
    tier: "一档",
    year: "2019",
    developer: "P-Studio",
    publisher: "Atlus",
    releaseDate: "2019-10-31",
    genre: "日式角色扮演",
    tags: ["美学", "日常", "音乐"],
    color: "#f14a45",
    color2: "#541617",
    mark: "P5",
    note: "UI、音乐、城市日常与怪盗幻想高度统一。它把一段漫长的青春生活做成了有节奏、有态度的舞台。",
    record: "在我玩过的游戏中，JRPG 视觉美学的天花板",
  },
  {
    id: "nier-automata",
    title: "尼尔：机械纪元",
    subtitle: "NieR: AUTOMATA",
    score: 9.7,
    tier: "一档",
    year: "2017",
    developer: "PlatinumGames",
    publisher: "Square Enix",
    releaseDate: "2017-02-23",
    genre: "动作角色扮演",
    tags: ["音乐", "氛围", "思辨"],
    color: "#c9c2ad",
    color2: "#49483f",
    mark: "2B",
    note: "音乐、废墟与存在主义彼此缠绕。通关之后留下的不是一个结论，而是一种很久都散不掉的空旷回声。",
    record: "在我玩过的游戏中，音乐与氛围共振的天花板",
  },
  {
    id: "sultans-game",
    title: "苏丹的游戏",
    subtitle: "SULTAN'S GAME",
    score: 9.6,
    tier: "一档",
    year: "2025",
    developer: "Double Cross",
    publisher: "2P Games",
    releaseDate: "2025-03-31",
    genre: "叙事卡牌",
    tags: ["权谋", "卡牌", "选择"],
    color: "#c99a54",
    color2: "#583b20",
    mark: "王",
    note: "卡牌只是表象，真正让我沉迷的是欲望、权力与命运的互相撕扯。每一次抉择都像在和故事共同犯罪。",
    record: "在我玩过的游戏中，卡牌叙事张力的天花板",
  },
  {
    id: "baldurs-gate-3",
    title: "博德之门 3",
    subtitle: "BALDUR'S GATE 3",
    score: 9.5,
    tier: "二档",
    year: "2023",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    genre: "角色扮演",
    tags: ["自由", "同伴", "选择"],
    color: "#d88b56",
    color2: "#542d2d",
    mark: "D20",
    note: "它真正尊重玩家的奇思怪想。选择并不只是台词分叉，而是能被世界认真接住、继续生长的行动。",
  },
  {
    id: "black-myth-wukong",
    title: "黑神话：悟空",
    subtitle: "BLACK MYTH: WUKONG",
    score: 9.4,
    tier: "二档",
    year: "2024",
    developer: "Game Science",
    publisher: "Game Science",
    releaseDate: "2024-08-20",
    genre: "动作角色扮演",
    tags: ["神话", "战斗", "美术"],
    color: "#d1a25f",
    color2: "#4c3822",
    mark: "悟",
    note: "熟悉的神话被做出了陌生、沉重而瑰丽的质感。最打动我的是那些藏在场景与唱词里的文化记忆。",
  },
  {
    id: "expedition-33",
    title: "光与影：33号远征队",
    subtitle: "CLAIR OBSCUR: EXPEDITION 33",
    score: 9.4,
    tier: "二档",
    year: "2025",
    developer: "Sandfall Interactive",
    publisher: "Kepler Interactive",
    releaseDate: "2025-04-24",
    genre: "角色扮演",
    tags: ["艺术", "音乐", "叙事"],
    color: "#7e9fc4",
    color2: "#2d3654",
    mark: "33",
    note: "像一幅会呼吸的油画，也像一场注定走向终点的舞台剧。艺术风格和悲剧气质牢牢绑在一起。",
  },
  {
    id: "wuchang",
    title: "明末：渊虚之羽",
    subtitle: "WUCHANG: FALLEN FEATHERS",
    score: 9.3,
    tier: "二档",
    year: "2025",
    developer: "Leenzee",
    publisher: "505 Games",
    releaseDate: "2025-07-24",
    genre: "类魂动作",
    tags: ["战斗", "黑暗", "探索"],
    color: "#a45e52",
    color2: "#422b31",
    mark: "羽",
    note: "阴郁世界、美术意象和高压战斗形成了鲜明辨识度。探索越深入，诡谲感越强。",
  },
  {
    id: "smt-vv",
    title: "真·女神转生 V Vengeance",
    subtitle: "SHIN MEGAMI TENSEI V: VENGEANCE",
    score: 9.2,
    tier: "二档",
    year: "2024",
    developer: "Atlus",
    publisher: "SEGA",
    releaseDate: "2024-06-14",
    genre: "日式角色扮演",
    tags: ["养成", "战斗", "神魔"],
    color: "#768bd7",
    color2: "#292d55",
    mark: "V",
    note: "队伍构筑和弱点博弈足够纯粹，恶魔收集又不断提供新目标。战斗系统本身就能支撑长时间沉浸。",
  },
  {
    id: "dynasty-warriors-origins",
    title: "真·三国无双：起源",
    subtitle: "DYNASTY WARRIORS: ORIGINS",
    score: 9.2,
    tier: "二档",
    year: "2025",
    developer: "Omega Force",
    publisher: "Koei Tecmo",
    releaseDate: "2025-01-17",
    genre: "战术动作",
    tags: ["军团战", "三国", "割草"],
    color: "#c95b45",
    color2: "#42211d",
    mark: "源",
    note: "大规模战场终于有了真正的压迫感。一骑当千的爽快与战线推进、军团对冲结合得更紧，熟悉的三国也被重新拉回群雄并起的原点。",
  },
  {
    id: "metaphor",
    title: "暗喻幻想：ReFantazio",
    subtitle: "METAPHOR: REFANTAZIO",
    score: 9.2,
    tier: "二档",
    year: "2024",
    developer: "Studio Zero",
    publisher: "Atlus · SEGA",
    releaseDate: "2024-10-11",
    genre: "日式角色扮演",
    tags: ["幻想", "政治", "旅途"],
    color: "#e5b443",
    color2: "#304561",
    mark: "M",
    note: "熟悉的日式养成骨架被放进更宏大的幻想政治寓言里。公路旅行感和世界议题同样鲜明。",
  },
  {
    id: "re4-remake",
    title: "生化危机 4 重制版",
    subtitle: "RESIDENT EVIL 4",
    score: 9.2,
    tier: "二档",
    year: "2023",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2023-03-24",
    genre: "生存恐怖",
    tags: ["射击", "节奏", "恐怖"],
    color: "#b7a163",
    color2: "#353b2f",
    mark: "RE4",
    note: "战斗资源、关卡推进与压力释放都经过精确计算。它几乎总能在我感到疲惫前给出新的刺激。",
  },
  {
    id: "stellar-blade",
    title: "剑星",
    subtitle: "STELLAR BLADE",
    score: 9.2,
    tier: "二档",
    year: "2024",
    developer: "Shift Up",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2024-04-26",
    genre: "动作角色扮演",
    tags: ["角色", "动作", "科幻"],
    color: "#9ed5cf",
    color2: "#32545b",
    mark: "EVE",
    note: "凌厉动作、末世科幻和角色魅力形成直接而有效的吸引力。招架成功时尤其有节奏感。",
    record: "在我玩过的游戏中，女性主角视觉设计的天花板",
  },
  {
    id: "rise-tomb-raider",
    title: "古墓丽影：崛起",
    subtitle: "RISE OF THE TOMB RAIDER",
    score: 9.1,
    tier: "二档",
    year: "2015",
    developer: "Crystal Dynamics",
    publisher: "Microsoft Studios",
    releaseDate: "2015-11-10",
    genre: "动作冒险",
    tags: ["探险", "解谜", "角色"],
    color: "#83aec5",
    color2: "#31465b",
    mark: "TR",
    note: "雪山遗迹、古墓解谜与劳拉的冒险者气质结合得很自然。它最像一部真正可以亲手参与的探险电影。",
  },
  {
    id: "ff16",
    title: "最终幻想 XVI",
    subtitle: "FINAL FANTASY XVI",
    score: 9.1,
    tier: "二档",
    year: "2023",
    developer: "Square Enix Creative Business Unit III",
    publisher: "Square Enix",
    releaseDate: "2023-06-22",
    genre: "动作角色扮演",
    tags: ["演出", "召唤兽", "史诗"],
    color: "#d37b62",
    color2: "#512c32",
    mark: "XVI",
    note: "召唤兽大战把电子游戏演出推向夸张而壮丽的尺度。它最精彩的瞬间像是整块屏幕都在燃烧。",
  },
  {
    id: "split-fiction",
    title: "双影奇境",
    subtitle: "SPLIT FICTION",
    score: 9.0,
    tier: "三档",
    year: "2025",
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    releaseDate: "2025-03-06",
    genre: "合作冒险",
    tags: ["双人", "创意", "冒险"],
    color: "#b56cdb",
    color2: "#40305d",
    mark: "2P",
    note: "创意像机关枪一样不断发射，几乎不允许一个玩法停留太久。双人协作时的惊喜尤其密集。",
  },
  {
    id: "detroit",
    title: "底特律：化身为人",
    subtitle: "DETROIT: BECOME HUMAN",
    score: 9.0,
    tier: "三档",
    year: "2018",
    developer: "Quantic Dream",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2018-05-25",
    genre: "互动叙事",
    tags: ["选择", "科幻", "电影感"],
    color: "#64b4df",
    color2: "#243d52",
    mark: "∆",
    note: "分支树让选择的重量变得可见。即使故事议题直白，亲手决定角色命运仍然有很强冲击力。",
  },
  {
    id: "re-requiem",
    title: "生化危机：安魂曲",
    subtitle: "RESIDENT EVIL REQUIEM",
    score: 8.9,
    tier: "三档",
    year: "2026",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2026-02-27",
    genre: "生存恐怖",
    tags: ["恐怖", "悬疑", "射击"],
    color: "#aab1a5",
    color2: "#343b37",
    mark: "REQ",
    note: "熟悉的生化危机节奏里加入了新的压迫方式。最吸引我的是探索未知空间时那种持续的不安。",
  },
  {
    id: "crimson-desert",
    title: "红色沙漠",
    subtitle: "CRIMSON DESERT",
    score: 8.8,
    tier: "三档",
    year: "2026",
    developer: "Pearl Abyss",
    publisher: "Pearl Abyss",
    releaseDate: "2026-03-19",
    genre: "开放世界动作",
    tags: ["开放世界", "动作", "冒险"],
    color: "#c46c52",
    color2: "#4d2a25",
    mark: "CD",
    note: "世界规模与动作表现都很有野心。那些意外遭遇和广阔地貌，让旅途始终保留未知感。",
  },
  {
    id: "tomb-raider-2013",
    title: "古墓丽影",
    subtitle: "TOMB RAIDER · 2013",
    score: 8.7,
    tier: "三档",
    year: "2013",
    developer: "Crystal Dynamics",
    publisher: "Square Enix",
    releaseDate: "2013-03-05",
    genre: "动作冒险",
    tags: ["生存", "探险", "成长"],
    color: "#b98a61",
    color2: "#4b372f",
    mark: "TR",
    note: "从求生者到冒险者的转变足够有力。荒岛氛围、攀爬与战斗共同塑造了紧凑的成长旅程。",
  },
  {
    id: "pragmata",
    title: "识质存在",
    subtitle: "PRAGMATA",
    score: 8.6,
    tier: "三档",
    year: "2026",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2026-04-17",
    genre: "科幻动作",
    tags: ["科幻", "搭档", "解谜"],
    color: "#9fb8d8",
    color2: "#303c59",
    mark: "月",
    note: "月面空间、机械谜题和搭档关系构成独特气质。它最迷人的部分，是冰冷技术中保留的柔软感。",
  },
  {
    id: "re-village",
    title: "生化危机 8：村庄",
    subtitle: "RESIDENT EVIL VILLAGE",
    score: 8.6,
    tier: "三档",
    year: "2021",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2021-05-07",
    genre: "生存恐怖",
    tags: ["哥特", "恐怖", "探索"],
    color: "#c9b58b",
    color2: "#454238",
    mark: "VIII",
    note: "不同区域像几座风格迥异的恐怖乐园。哥特童话感比单纯的惊吓更让我记得住。",
  },
  {
    id: "re2-remake",
    title: "生化危机 2 重制版",
    subtitle: "RESIDENT EVIL 2",
    score: 8.5,
    tier: "三档",
    year: "2019",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2019-01-25",
    genre: "生存恐怖",
    tags: ["资源", "追逐", "探索"],
    color: "#b4463e",
    color2: "#3e2528",
    mark: "RE2",
    note: "警局空间被反复折叠利用，资源压力让每条走廊都有意义。暴君的脚步声至今仍有条件反射般的压迫感。",
  },
  {
    id: "re7",
    title: "生化危机 7",
    subtitle: "RESIDENT EVIL 7: BIOHAZARD",
    score: 8.4,
    tier: "三档",
    year: "2017",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2017-01-24",
    genre: "生存恐怖",
    tags: ["第一人称", "压迫", "探索"],
    color: "#9d9a6d",
    color2: "#37392e",
    mark: "VII",
    note: "第一人称让距离感消失，宅邸里的污浊气息几乎贴到脸上。前半段的压迫感尤其强。",
  },
  {
    id: "it-takes-two",
    title: "双人成行",
    subtitle: "IT TAKES TWO",
    score: 8.4,
    tier: "三档",
    year: "2021",
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    releaseDate: "2021-03-26",
    genre: "合作冒险",
    tags: ["双人", "创意", "轻松"],
    color: "#df8f58",
    color2: "#4e3955",
    mark: "2",
    note: "几乎每章都在更换玩法，用非常直观的协作把两个人拉进同一个节奏里。",
  },
  {
    id: "miside",
    title: "米塔",
    subtitle: "MiSide",
    score: 8.3,
    tier: "三档",
    year: "2024",
    developer: "AIHASTO",
    publisher: "IndieArk",
    releaseDate: "2024-12-11",
    genre: "心理恐怖",
    tags: ["反差", "角色", "恐怖"],
    color: "#ee78a5",
    color2: "#4f2744",
    mark: "M",
    note: "可爱外壳与失控感形成的反差非常有效。它知道玩家为什么会被角色吸引，也知道如何把这种吸引变成恐惧。",
  },
  {
    id: "love-is-all-around",
    title: "完蛋！我被美女包围了！",
    subtitle: "LOVE IS ALL AROUND",
    score: 8.2,
    tier: "三档",
    year: "2023",
    developer: "intiny",
    publisher: "intiny",
    releaseDate: "2023-10-18",
    genre: "真人互动",
    tags: ["恋爱", "真人", "轻松"],
    color: "#ef8f95",
    color2: "#51313a",
    mark: "♥",
    note: "真人影像带来的临场感很直接，轻松、热闹，也足够知道如何不断给玩家情绪反馈。",
  },
  {
    id: "dying-light",
    title: "消逝的光芒",
    subtitle: "DYING LIGHT",
    score: 8.1,
    tier: "三档",
    year: "2015",
    developer: "Techland",
    publisher: "Warner Bros. Interactive Entertainment",
    releaseDate: "2015-01-27",
    genre: "开放世界生存",
    tags: ["跑酷", "丧尸", "昼夜"],
    color: "#d58d43",
    color2: "#4b3b23",
    mark: "DL",
    note: "跑酷让移动本身就有乐趣，而夜晚则把熟悉城市瞬间变成危险猎场。昼夜反差是它最鲜明的记忆。",
  },
  {
    id: "re3-remake",
    title: "生化危机 3 重制版",
    subtitle: "RESIDENT EVIL 3",
    score: 8.0,
    tier: "三档",
    year: "2020",
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2020-04-03",
    genre: "生存恐怖",
    tags: ["动作", "追逐", "城市"],
    color: "#d46e50",
    color2: "#4c292a",
    mark: "RE3",
    note: "流程偏短，但城市逃亡的速度感和吉尔的角色魅力仍然足够突出，适合一口气通关。",
  },
  {
    id: "balatro",
    title: "小丑牌",
    subtitle: "BALATRO",
    score: 8.0,
    tier: "三档",
    year: "2024",
    developer: "LocalThunk",
    publisher: "Playstack",
    releaseDate: "2024-02-20",
    genre: "策略卡牌",
    tags: ["构筑", "策略", "上瘾"],
    color: "#e15c5b",
    color2: "#35466c",
    mark: "J",
    note: "规则简单，但数值联动会迅速长成一台属于自己的组合机器。再来一局总是比停下来容易。",
  },
];

export const dimensions = [
  {
    id: "character",
    label: "角色共鸣",
    value: 96,
    description: "我最容易被有持续陪伴感、关系会逐渐生长的角色打动。",
    gameIds: ["ff7-remake", "ff7-rebirth", "persona-5-royal", "stellar-blade"],
  },
  {
    id: "atmosphere",
    label: "氛围余韵",
    value: 93,
    description: "音乐、美术与世界气质结合时，通关之后仍会在记忆里继续发生。",
    gameIds: ["nier-automata", "expedition-33", "re-village", "pragmata"],
  },
  {
    id: "story",
    label: "叙事选择",
    value: 89,
    description: "我喜欢故事尊重玩家，并让选择真正改变人物关系与世界回声。",
    gameIds: ["sultans-game", "baldurs-gate-3", "detroit", "metaphor"],
  },
  {
    id: "combat",
    label: "战斗节奏",
    value: 87,
    description: "比起纯粹高难，我更在意反馈、构筑与演出是否能形成连续的心流。",
    gameIds: ["ff7-remake", "re4-remake", "black-myth-wukong", "smt-vv"],
  },
];
